### ISSUE TITLE
pip package

### ISSUE THREAD

**Issue by GlennWSo** [mloskot/github-label-maker#2]
My pain is to use i need keep the source code and know the path to it.
currently i do somthing like:
``` bash
python3 path/to/github_label_maker  ...
```
Would be nice if this project was packaged. 
So it can be installed with pip.
and then used like this:

``` bash
github_label_maker ...
```

**Comment by mloskot** [comment]
Yes, it would be nice indeed, but as you noticed development of this project is not very active and I'm not experienced with packaging for PIP. So, I will appreciate any help and pull requests.

**Comment by GlennWSo** [comment]
i created a pull request #3 that I believe resolves this issue (and hopefully without braking anything)
A would appreciate your review and feedback :)

if you are satisfied with my proposed changes, the next logical step imo is to push this package to:
[pypi](https://pypi.org/)

**Comment by mloskot** [comment]
@GlennWSo I've just merged, see my https://github.com/mloskot/github-label-maker/pull/3#pullrequestreview-1184445126 Thank you!
